# Generated by Django 4.0.2 on 2022-04-19 12:14

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo', models.ImageField(upload_to='media/coders/')),
                ('description', ckeditor.fields.RichTextField()),
                ('city', models.CharField(max_length=255)),
                ('level_type', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], max_length=255)),
                ('job_type', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Remote-work', 'Remote-work'), ('Internship', 'Internship')], max_length=255)),
                ('developer_type', models.CharField(choices=[('.NET', '.NET'), ('React', 'React'), ('Nodejs', 'Nodejs'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django')], max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
