# Generated by Django 4.0.2 on 2022-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='job_type',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Remote-work', 'Remote-work'), ('Internship', 'Internship')], max_length=255),
        ),
        migrations.AlterField(
            model_name='coder',
            name='level_type',
            field=models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], max_length=255),
        ),
    ]
