# Generated by Django 4.0.2 on 2022-03-06 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0002_alter_coder_job_type_alter_coder_level_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='coder',
            name='skills',
            field=models.ManyToManyField(to='coders.Skill'),
        ),
    ]
