# Generated by Django 4.0.2 on 2022-04-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0002_alter_coder_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='developer_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='coder',
            name='job_type',
            field=models.CharField(max_length=255),
        ),
    ]
