# Generated by Django 4.0.2 on 2022-04-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0003_alter_coder_developer_type_alter_coder_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='job_type',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Remote-work', 'Remote-work')], max_length=255),
        ),
    ]
