# Generated by Django 4.0.2 on 2022-03-08 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0004_rename_skills_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='video_url',
        ),
    ]
