# Generated by Django 3.1.3 on 2022-04-06 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0007_alter_coder_id_alter_skill_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
