# Generated by Django 3.1.3 on 2022-04-11 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0008_auto_20220406_2235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coder',
            name='skills',
        ),
        migrations.AddField(
            model_name='coder',
            name='skills',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
