# Generated by Django 3.1.3 on 2022-04-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0009_auto_20220411_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
