# Generated by Django 4.0 on 2022-04-11 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coders', '0010_coder_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
