# Generated by Django 4.0 on 2022-04-13 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_id'),
        ('coders', '0011_alter_coder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coder',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
