# Generated by Django 3.1.3 on 2022-04-11 16:02

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='media/companies/')),
                ('city', models.CharField(max_length=255)),
                ('job_type', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Remote-work', 'Remote-work'), ('Internship', 'Internship')], max_length=255)),
                ('level_type', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], max_length=255)),
                ('developer_type', models.CharField(choices=[('.NET', '.NET'), ('React', 'React'), ('Nodejs', 'Nodejs'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django')], max_length=255)),
                ('no_of_vacancies', models.PositiveIntegerField()),
                ('deadline', models.DateTimeField()),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
