# Generated by Django 4.0.2 on 2022-04-19 12:14

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=10)),
                ('company_location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/companies/')),
                ('job_type', models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Remote-work', 'Remote-work'), ('Internship', 'Internship')], max_length=255)),
                ('level_type', models.CharField(choices=[('Fresher', 'Fresher'), ('Junior', 'Junior'), ('Mid-level', 'Mid-level'), ('Senior', 'Senior')], max_length=255)),
                ('developer_type', models.CharField(choices=[('.NET', '.NET'), ('React', 'React'), ('Nodejs', 'Nodejs'), ('PHP', 'PHP'), ('Laravel', 'Laravel'), ('Angular', 'Angular'), ('Django', 'Django')], max_length=255)),
                ('no_of_vacancies', models.PositiveIntegerField()),
                ('deadline', models.DateField()),
                ('skills', models.CharField(blank=True, max_length=255, null=True)),
                ('salary', models.CharField(max_length=20)),
                ('description', ckeditor.fields.RichTextField()),
                ('cosinevalue', models.FloatField(null=True)),
                ('created_date', models.DateField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
