# Generated by Django 4.0.2 on 2022-04-19 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254)),
                ('company_phone', models.CharField(max_length=10)),
                ('company_location', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/companies/')),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_location',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job',
            name='company_phone',
        ),
        migrations.RemoveField(
            model_name='job',
            name='photo',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobs.company'),
        ),
    ]
