# Generated by Django 4.0.2 on 2022-04-19 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_company_remove_job_company_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_location',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='company_phone',
            new_name='phone',
        ),
    ]
