# Generated by Django 4.0.2 on 2022-04-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_rename_company_location_company_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.AlterField(
            model_name='job',
            name='cosinevalue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('Part-time', 'Part-time'), ('Full-time', 'Full-time'), ('Internship', 'Internship')], max_length=255),
        ),
    ]
