# Generated by Django 4.0 on 2022-04-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_title_alter_job_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='created_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
