# Generated by Django 4.0.2 on 2022-04-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cosinevalue',
            field=models.IntegerField(null=True),
        ),
    ]
