# Generated by Django 4.0.2 on 2022-04-15 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_cosinevalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='cosinevalue',
            field=models.FloatField(null=True),
        ),
    ]
