# Generated by Django 4.0.2 on 2022-02-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirecoders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hirecoder',
            name='coder_developer_type',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
