# Generated by Django 3.1.3 on 2022-03-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirecoders', '0002_hirecoder_coder_developer_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirecoder',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
