# Generated by Django 4.0.2 on 2022-03-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hirecoders', '0003_auto_20220319_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hirecoder',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
