# Generated by Django 4.0.2 on 2022-04-19 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Slider',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
