# Generated by Django 4.0.2 on 2022-02-06 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='insta_link',
            new_name='linkedin_link',
        ),
    ]
